# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Variable declaration
#
## change this to be your git root.  the full path is built based on $git_root + "/vPC" - don't forget the trailing slash on the git_root
git_root = '~/projects/'

Vagrant.configure(2) do |config|

  config.ssh.private_key_path = "~/.ssh/vagrant-insecure"

  config.vm.provider "virtualbox" do |vb|
    config.vm.box = "hashicorp/precise64"
    # download the vbox from the Epidemico installer service if it doesn't exist locally
    config.vm.box_download_insecure = true
    config.vm.network :forwarded_port, guest: 443, host: 4443
    config.vm.network :forwarded_port, guest: 80, host: 8000
    config.vm.synced_folder git_root + "lh", "/data/applications/lh", create: true
    vb.memory = 4096
    #vb.gui = true # will pop up the virtualbox console window
  end

  # install puppet
  config.vm.provision "shell", :inline => <<-SHELL
    # install puppet
    wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb &> /dev/null
    dpkg -i puppetlabs-release-trusty.deb &> /dev/nul
    apt-get update
    apt-get install puppet -y
  SHELL

  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
    puppet.hiera_config_path = "hiera.yaml"
  end

end
